### ISSUE TITLE
OnTap function Bug 

### ISSUE THREAD

**Issue by FlavioBarros13** [DogeeeXD/Breathing-Collection#1]
Hi mate , Great package ....

1. There's a bug in the "OnTap" function is not working on the latest's 2 versions.
I downgraded to "breathing_collection: ^0.1.5" to test and saw that it's working.
2.I saw that you are using InkWell to get the click listener, It would be awesome to have the option to choose the button splash screen color, because when the button is pressed at the moment it shows a squared white splash which extends out of the button radius ,being the button a circular.

Other than that everything else perfect!! great package

**Comment by alanchan-dev** [comment]
I'll look into it as soon as possible

**Comment by alanchan-dev** [comment]
Hi, thanks for reporting the issue, 
1. I've fixed the onTap bug in the latest version.
2. I removed the splash effect from the InkWell as it wasn't intended to have a splash effect. (It looks ugly when overlapping with the glowing effect)

Feel free to open an feature request issue if you think the splash effect option is necessary.

**Comment by FlavioBarros13** [comment]
Working perfectly! great work
